apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: randomquotes-java
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: 'https://192.168.11.167:6445'
      - cluster: stage
        url: 'https://192.168.11.167:6444'
  template:
    metadata:
      name: '{{cluster}}-randomquotes-java'
    spec:
      project: default
      source:
#       repoURL: https://github.com/fdaluisio/app-of-apps-randomquotes-java-infra.git
        repoURL: https://github.com/fdaluisio/RandomQuotes-Java-infra.git
        targetRevision: HEAD
        path: randomquotes-java
        helm:                                                                                                                                                                
          valueFiles:                                                                                                                                                        
            - 'values-{{cluster}}.yaml'
          releaseName: '{{cluster}}-randomquotes-java'
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:                                                                                                                                                            
        syncOptions:                                                                                                                                                         
          - CreateNamespace=true                                                                                                                                             
        automated:                                                                                                                                                           
          selfHeal: true                                                                                                                                                     
          prune: true                                                                                                                                                        
          allowEmpty: true   
